# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-08 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_auto_20180219_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealitem',
            name='item_status',
            field=models.BooleanField(default=0),
        ),
    ]
