# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-08 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_mealitem_item_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealitem',
            name='item_status',
        ),
        migrations.AddField(
            model_name='mealitem',
            name='item_consumed',
            field=models.BooleanField(default=0, verbose_name='Status'),
        ),
    ]
