# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-23 07:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180221_0550'),
        ('core', '0010_auto_20180219_1951'),
    ]

    operations = [
    ]
