# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-07 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20180219_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='drop_set',
            field=models.BooleanField(default=False, verbose_name='Drop set'),
        ),
    ]
